{
    "Auto Join Equipper": {
        "Macro Equipper": {
            "Enable": false,
            "Auto Join Macro": []
        },
        "Team Equipper": {
            "Enable": true,
            "Auto Join Team": {
                "Dungeon Joiner": 2,
                "Stage Joiner": 0,
                "Regular Challenge Joiner": 1,
                "Summer Event Joiner": 0,
                "Worldline Joiner": 1,
                "Pirate Dynasty Joiner": 0,
                "Spring Event Joiner": 0,
                "Boss Event Joiner": 4,
                "Weekly Challenge Joiner": 1,
                "Limitless Odyssey Joiner": 0,
                "Odyssey Joiner": 0,
                "Summer Portal Joiner": 0,
                "Legend Stage Joiner": 0,
                "Boss Bounties Joiner": 1,
                "Adventure Odyssey Joiner": 0,
                "Fall Event Joiner": 6,
                "Raid Joiner": 4,
                "Daily Challenge Joiner": 1,
                "Rift Joiner": 3
            }
        }
    },
    "Gold Buyer": {
        "Enable": false,
        "Item": {
            "Brand": true,
            "Magic Pendant": true,
            "Yellow Essence Stone": false,
            "Transfigured Soul": true,
            "Rainbow Essence Stone": false,
            "Super Stat Chip": true,
            "Kuinshi Medallion": true,
            "Strange Fruit": true,
            "Red Essence Stone": false,
            "Blue Essence Stone": false,
            "Stat Chip": true,
            "Green Essence Stone": false,
            "DMCA Voucher": false,
            "Purple Essence Stone": false,
            "Crystal": false,
            "Senzu Bean": false,
            "Pink Essence Stone": false,
            "Ramen": true,
            "Gears": true,
            "Giant Serum": true,
            "Chocolate Bars": true,
            "Item Finder": false,
            "Doggy Bone": false
        }
    },
    "Fall Event": {
        "Fall Event Joiner": {
            "Auto Join": false,
            "Mode": "Infinite"
        }
    },
    "Dungeon Joiner": {
        "Auto Join": false,
        "Stage": "Anniversary Dungeon",
        "Act": "Act9"
    },
    "Stage Joiner": {
        "Nightmare Mode": false,
        "Join Highest": false,
        "Auto Join": false,
        "Join Lowest Clear": false
    },
    "Fall Portal Joiner": {
        "Buy if out of Portal": false,
        "Tier Cap": 10,
        "Auto Join": false,
        "Ignore Modifier": {
            "Strong": false,
            "Thrice": false,
            "Regen": false,
            "Fast": false,
            "Revitalize": false,
            "Drowsy": false,
            "Exploding": false,
            "Dodge": false,
            "Quake": false,
            "Immunity": false,
            "Shielded": false,
            "Champions": false
        },
        "Auto Next": false,
        "Portal Reward Picker": {
            "Enable": false,
            "Ignore Modifier": {
                "Strong": false,
                "Thrice": false,
                "Regen": false,
                "Fast": false,
                "Revitalize": false,
                "Drowsy": false,
                "Exploding": false,
                "Dodge": false,
                "Quake": false,
                "Immunity": false,
                "Shielded": false,
                "Champions": false
            }
        }
    },
    "Macros": {
        "Secret Portal Macro": [],
        "Legend Stage Macro": [],
        "Macro Retry Limit": 0,
        "Ignore Macro Timing": true,
        "Dungeon Macro": [],
        "Play": false,
        "Auto Equip": false,
        "Odyssey Macro": [],
        "Macro": "Spring55s_1",
        "Raid Macro": [],
        "Boss Bounties Macro": [],
        "Rift Macro": [],
        "Limitless Odyssey Macro": [],
        "Fall Portal Macro": {
            "Lich Kings Throne": "Fall"
        },
        "Challenge Macro": [],
        "No Ignore Sell Timing": true,
        "Worldline Macro": [],
        "Boss Event Macro": [],
        "Summer Portal Macro": [],
        "Spring Event Macro": []
    },
    "Summer Event": {
        "Summer Event Joiner": {
            "Auto Event": false,
            "Auto Fix No Consumable": true,
            "Auto Join": false,
            "Auto Type": "Farm Currency"
        }
    },
    "Pirate Dynasty Joiner": {
        "Auto Farm Essence": false,
        "Auto Join": false,
        "Auto Pirate Dynasty": {
            "Enabled": false,
            "Character": "ElasticCaptainPirate",
            "Difficulty": "Normal"
        }
    },
    "Adventure Odyssey Joiner": {
        "Auto Basic Card": {
            "Enabled": true,
            "Prioritize": {
                "Golden Age": 26,
                "Infection": 9,
                "Shop Cleaner": 32,
                "Slayer Rounds": 7,
                "Volatile Demise": 16,
                "Cleansing Pool": 33,
                "Limit Break": 25,
                "Ambush": 5,
                "Boxing Gloves": 4,
                "Extended Duration": 12,
                "Treasure Map Fragment": 13,
                "Affinity": 9999999,
                "Base Shield": 10,
                "Concussive Blast": 6,
                "Serrated Tips": 2,
                "Unstoppable Force": 29,
                "Double Tap": 23,
                "Delicate Flower": 1,
                "Crippling Field": 27,
                "The Best Defense…": 19,
                "Essence Collector": 24,
                "Adrenaline Shot": 22,
                "Quick Charge": 14,
                "Luckcatcher": 28,
                "Battle Frenzy": 11,
                "True Strike": 31,
                "Military Training": 8,
                "Potent Toxins": 15,
                "Precision Optics": 3,
                "Numbing Agent": 18,
                "Spoils of War": 30,
                "Painful Gains": 17,
                "Resource Overflow": 21
            }
        },
        "Auto Stitches Shop": {
            "Enabled": true,
            "Buy Unit Memoria": {
                "The Beast King": false,
                "Water Goddess's Cheer": false,
                "Enthusiastic Walks": true,
                "Armored Mage's Day Off": false,
                "Perpetual Motion": false,
                "Messenger of Destruction": false,
                "Damage Boost I": false,
                "Range Boost I": false,
                "Empty Reflections": false,
                "Golden Obsessions": false,
                "Death, Resurrected": false,
                "One Above All": false,
                "Anger vs Discipline": false,
                "Drops of Serenity": false,
                "Frozen Admiral": false,
                "Scrap Metal Master": false,
                "Power Surge": false,
                "Artist's Blessing": false,
                "Snip Snip": false,
                "My Brother!": false,
                "King of the Trash": false,
                "Trust of Others": false,
                "Peak of Shinobi": true,
                "Shall Know Pain": false,
                "Bond of Master and Disciple": false,
                "He Laughed": false,
                "Late Night Shift": false,
                "Company Captain's Presence": false,
                "Regretful Past": false,
                "Destroyer of Worlds": false,
                "Royal Flush": false,
                "Gaze of the Strongest": false,
                "The True Savior": false,
                "A Father's Sacrifice": false,
                "Ice Queen's Rest": false,
                "Master of Toads": false,
                "Sinful Priest": false,
                "Hellfire": false,
                "Gambling Fanatic": false,
                "Lifeforce Absorption": false,
                "Lord of the Fairies": false,
                "Speed Boost I": false,
                "Tough Bunny": false,
                "Along Came a Spider": false,
                "Immortal Divine General": false,
                "Deceptive Innocence": false,
                "Restricted By the Heavens": false,
                "Shackled Sight": false,
                "DoT Amplifier": false,
                "Battle of the Strongest": false,
                "By the Book": false,
                "Revenge of the Cursed One": false,
                "Blazing Inferno": false,
                "Ultimate Deceiver": false,
                "Purveyor of Peace": false,
                "POWAHH!!!": false,
                "Unlikely Doctor": false,
                "Graceful Mecha": false,
                "Young Entrepreneur": false,
                "All I've Got": false,
                "Devoted Dedication": false,
                "Goddess of Spring": false
            },
            "Buy Unit Trait": {
                "Fortune": false,
                "Monarch": false,
                "Solar": false,
                "Range": false,
                "Scholar": false,
                "Vigor": false,
                "Swift": false,
                "Marksman": false,
                "Prodigy": false,
                "Blitz": false,
                "Deadeye": true,
                "Ethereal": false
            },
            "Buy Starter Card": {
                "Full Deck": true,
                "Memorized": true,
                "Not Basic": true,
                "Flight": true,
                "Handpicked": true,
                "Abundance": true,
                "Hoarder": true,
                "Power Trip": true,
                "I'm Familiar": true,
                "High Value": true,
                "Treasure Hunter": true,
                "Jack Pot": true,
                "Chosen One": true,
                "Gold Thread": true
            },
            "Buy Basic Card": {
                "Golden Age": true,
                "Infection": false,
                "Shop Cleaner": true,
                "Slayer Rounds": false,
                "Volatile Demise": false,
                "Cleansing Pool": true,
                "Limit Break": true,
                "Ambush": false,
                "Boxing Gloves": false,
                "Extended Duration": false,
                "Treasure Map Fragment": false,
                "Affinity": true,
                "Base Shield": false,
                "Concussive Blast": false,
                "Serrated Tips": false,
                "Unstoppable Force": true,
                "Double Tap": true,
                "Delicate Flower": true,
                "Crippling Field": true,
                "The Best Defense…": true,
                "Essence Collector": true,
                "Adrenaline Shot": false,
                "Quick Charge": false,
                "Luckcatcher": true,
                "Battle Frenzy": false,
                "True Strike": true,
                "Military Training": false,
                "Potent Toxins": false,
                "Precision Optics": false,
                "Numbing Agent": false,
                "Spoils of War": true,
                "Painful Gains": false,
                "Resource Overflow": true
            }
        },
        "Auto Route Atlas": {
            "Enabled": true,
            "Floor Prioritize": {
                "Elite": 4,
                "Battle": 1,
                "Treasure": 2,
                "Boss": 5,
                "Shop": 3
            },
            "Second Floor Prioritize": {
                "Elite": 1,
                "Battle": 2,
                "Treasure": 4,
                "Boss": 5,
                "Shop": 3
            },
            "Second Prioritize Floor": 67
        },
        "Character": "Tuji (Sorcerer Killer)",
        "Auto Choose Unit Reward": true,
        "Slot 2": "Memorized",
        "Auto Character Card": {
            "Enabled": true,
            "Prioritize": {
                "Shinobi God (Infinite Dreams)": {
                    "Free Ascension": 12,
                    "Endless Ninjutsu": 11,
                    "Ninjutsu Payout": 1,
                    "Boundless Growth": 5,
                    "Afflicted Arrival": 9997,
                    "Infinite Dream Slot": 9999,
                    "Elite Claim": 9998,
                    "Infinite Dream Stun": 9,
                    "Shared Ninjutsu": 8,
                    "Layered Slumber": 9996,
                    "Stacked Afflictions": 991,
                    "Lone Shinobi": 3
                },
                "Tuji (Sorcerer Killer)": {
                    "No Wasted Yen": 0,
                    "Unbound Arsenal": 9998,
                    "Total Restriction": 9999,
                    "Methodical Planning": 3,
                    "Shieldbreaker's Momentum": 10001,
                    "Relentless Growth": 4,
                    "Heavenly Punishment": 9997,
                    "Cursed Gift": 9995,
                    "Heavenly Restriction": 10000,
                    "Shared Killing Intent": 9994,
                    "Inventory Mastery": 6,
                    "Lone Sorcerer": 9
                },
                "Iscanur (Pride)": {
                    "Everlasting Noon": 8,
                    "Scorching Presence": 1,
                    "Instant Noon": 3,
                    "Lion's Sin": 6,
                    "Burning Pride": 2,
                    "Sunlit Sacrifice": 12,
                    "Shield-Piercing Sun": 7,
                    "Opening Ultimate": 9996,
                    "Unyielding Ultimate": 5,
                    "Peak Arrival": 9997,
                    "Solar Expansion": 9999,
                    "Double Hour": 9998
                },
                "Manipulator (Spider)": {
                    "Webbed Affliction": 11,
                    "Bleed Out": 9995,
                    "Universal Vanity": 9996,
                    "Piercing Toxins": 5,
                    "Amplified Affliction": 3,
                    "Crit Followup": 8,
                    "Bleed Multiplication": 10,
                    "Endless Growth": 9997,
                    "Compound Affliction": 7,
                    "Endless Web": 9999,
                    "Hyper Tempo": 1,
                    "Multiplied Negativity": 9998
                },
                "Rogita (Super 4)": {
                    "Efficient Fusion": 9996,
                    "Teleport Payout": 1,
                    "Clone Evolution": 9997,
                    "Clone Momentum": 9998,
                    "Training Grounds": 9999,
                    "Teleport Power-Up": 4,
                    "Limitless Active": 3,
                    "Mirrored Impact": 6,
                    "Wave Training": 2,
                    "Afterimage Warp": 9994,
                    "Blink Strike": 5,
                    "Extra Clones": 9995
                },
                "Luce (Hacker)": {
                    "Mass Deployment": 6,
                    "Signing Bonus": 7,
                    "Wild Code": 9996,
                    "Avenge Protocol": 9999,
                    "Full Sync": 12,
                    "Exploit Stack": 5,
                    "Bounty Protocol": 9997,
                    "Persistent Memory": 9,
                    "Shared Firmware": 3,
                    "Backup Online": 9998,
                    "Overclocked": 10,
                    "Exploit Variety": 11
                },
                "Elastic Captain (Cog 5th)": {
                    "Base Build": 9996,
                    "Triple Strike": 6,
                    "Meter Compensation": 3,
                    "Meter Mastery": 7,
                    "Sun God Vitality": 9,
                    "Floor Power": 9997,
                    "Global Reach": 8,
                    "Frenzied Sun God": 12,
                    "Boss Promotion": 9999,
                    "Reduced Cooldowns": 11,
                    "One True Captain": 10,
                    "Cog Multiplier": 9998
                },
                "Song Jinwu and Igros": {
                    "Expanded Meter": 5,
                    "Elite Knight Ranks": 4,
                    "Mana Reclaim": 8,
                    "Boss-Room Legion": 9997,
                    "Elite Momentum": 11,
                    "Duplicated Elite": 9999,
                    "Elite Bounty": 9996,
                    "Total Meter Offering": 12,
                    "Shadow Meter": 1,
                    "Elite Shadow Assault": 9998,
                    "Growing Nuke": 3,
                    "Summoner's Arrival": 7
                },
                "Hellkiller (Slayer)": {
                    "Boss Slayer": 3,
                    "Auto Upgrader": 4,
                    "Tearing Strike": 11,
                    "Shotgun Specialist": 1,
                    "Empty Magazine": 10,
                    "Pure Power": 2,
                    "Infinite Hellwalker": 7,
                    "Co-op Shooting": 6,
                    "Echoing Wounds": 9,
                    "Fixed Speed": 8,
                    "Killer Momentum": 5
                },
                "Divalo (Requiem)": {
                    "Echoes of Erasure": 10,
                    "Counter Storm": 9,
                    "Echoed Erasure": 5,
                    "King's Court": 2,
                    "Erasure Reduced": 9999,
                    "Rending Strikes": 8,
                    "Time Slowing": 3,
                    "Royal Court": 9997,
                    "Inescapable Status": 12,
                    "Affliction Bonus": 9995,
                    "Max Ascended": 9996,
                    "Full Erasure": 9998
                },
                "Demon Leader (Control)": {
                    "Word of Death": 9996,
                    "Tearing Bite": 5,
                    "Unbound Chains": 9994,
                    "Shared Authority": 6,
                    "Gift of the Devil": 9995,
                    "Eager Command": 3,
                    "Bark For Me": 9,
                    "Reign of Control": 9999,
                    "Merciful Tyrant": 9997,
                    "Absolute Command": 9998,
                    "Crippling Wounds": 9993,
                    "Devil's Contract": 1
                },
                "Regnaw (Rage)": {
                    "Escalating Fury": 12,
                    "Elite Conquest": 9998,
                    "Nullifying Strike": 5,
                    "Placement Shockwave": 9,
                    "Shieldbreaker": 2,
                    "Critical Shockwave": 6,
                    "Rage Slots": 11,
                    "Rageful Arrival": 9997,
                    "Critical Rage": 3,
                    "All-Range Rage": 9996,
                    "Rage Bounty": 1,
                    "Monarch's Breakthrough": 99999
                },
                "Alocard (Vampire King)": {
                    "Bounty of the Hunt": 2,
                    "Swarming Vitality": 6,
                    "Master of Thralls": 9999,
                    "Crimson Wave": 9996,
                    "Bloodlust": 5,
                    "Seal of Death": 12,
                    "Unsealed Power": 9997,
                    "Legions of the Night": 3,
                    "Blood Tithe": 7,
                    "Risen Horde": 4,
                    "Endless Release": 9998,
                    "Lone Monarch": 9
                },
                "Yomomata (Captain)": {
                    "Ascending Captain": 7,
                    "Shared Reaping": 9999,
                    "Searing Pierce": 2,
                    "North's Pyre": 993,
                    "Burning to Bleed": 994,
                    "Twin Specters": 9998,
                    "Takedown Spawn": 9996,
                    "Endless South": 3,
                    "Lingering Burn": 9,
                    "Soul Continuation": 9997,
                    "Eternal Bankai": 995,
                    "Intense Bankai": 10
                }
            }
        },
        "Auto Join": false,
        "Auto Buy Itches": true,
        "Slot 1": "Abundance"
    },
    "Legend Stage Joiner": {
        "Auto Join": false
    },
    "Odyssey Joiner": {
        "Second Team": 2,
        "Auto Join": false,
        "Buy Card": {
            "Golden Age": false,
            "Infection": false,
            "Shop Cleaner": false,
            "Slayer Rounds": false,
            "Battle Frenzy": false,
            "Cleansing Pool": false,
            "Limit Break": false,
            "Ambush": false,
            "Boxing Gloves": false,
            "Extended Duration": false,
            "Crippling Field": false,
            "Affinity": false,
            "Base Shield": false,
            "Concussive Blast": false,
            "Serrated Tips": false,
            "Spoils of War": false,
            "Double Tap": false,
            "Delicate Flower": false,
            "Treasure Map Fragment": false,
            "The Best Defense…": false,
            "Essence Collector": false,
            "Adrenaline Shot": false,
            "Quick Charge": false,
            "Luckcatcher": false,
            "Volatile Demise": false,
            "True Strike": false,
            "Military Training": false,
            "Potent Toxins": false,
            "Precision Optics": false,
            "Numbing Agent": false,
            "Unstoppable Force": false,
            "Painful Gains": false,
            "Resource Overflow": false
        },
        "Cash Out Floor": 5,
        "Intensity": 200,
        "First Team": 1
    },
    "Summer Portal Joiner": {
        "Tier Cap": 9,
        "Auto Next": false,
        "Portal Type": "Scorching Fate Trial",
        "Join Secret": false,
        "Portal Reward Picker": {
            "Enable": true,
            "Ignore Modifier": {
                "Strong": false,
                "Drowsy": false,
                "Regen": false,
                "Fast": false,
                "Revitalize": true,
                "Champions": false,
                "Exploding": false,
                "Dodge": false,
                "Immunity": false,
                "Shielded": true,
                "Quake": false,
                "Thrice": false
            }
        },
        "Ignore Modifier": {
            "Strong": false,
            "Drowsy": false,
            "Regen": false,
            "Fast": false,
            "Revitalize": false,
            "Champions": false,
            "Exploding": false,
            "Dodge": false,
            "Immunity": false,
            "Shielded": false,
            "Quake": false,
            "Thrice": false
        },
        "Auto Join": false
    },
    "Claimer": {
        "Auto Claim Battle Pass": false,
        "Auto Claim Quest": true,
        "Auto Claim Milestone": true,
        "Auto Claim Achievement": true,
        "Auto Claim Daily Reward": true,
        "Auto Claim Collection": true,
        "Auto Claim Enemy Index": true,
        "Auto Claim Collection Milestone": true
    },
    "Gameplay": {
        "Auto Sell": {
            "Auto Sell Farm": {
                "Enable": false,
                "Wave": 1,
                "Stage Type": {
                    "Odyssey": true,
                    "Challenge": true,
                    "Portal": true,
                    "Worldline": true,
                    "Legend Stage": true,
                    "BossEvent": true,
                    "Dungeon": true,
                    "Infinite": true,
                    "Rift": true,
                    "Story": true,
                    "Raid": true
                }
            },
            "Auto Sell Unit": {
                "Enable": false,
                "Wave": 1,
                "Stage Type": {
                    "Odyssey": true,
                    "Challenge": true,
                    "Portal": true,
                    "Worldline": true,
                    "Legend Stage": true,
                    "BossEvent": true,
                    "Dungeon": true,
                    "Infinite": true,
                    "Rift": true,
                    "Story": true,
                    "Raid": true
                }
            }
        },
        "Unit Mechanic": {
            "Tempest Pirate (Navigator)": {
                "Auto Dig Chest": true
            },
            "Iscanur (Pride)": {
                "Burn Units": {
                    "Enable": true,
                    "Slots": {
                        "1": false,
                        "2": true,
                        "3": false,
                        "4": false,
                        "5": false,
                        "6": false
                    },
                    "Stage Type": {
                        "Odyssey": true,
                        "Challenge": true,
                        "Portal": true,
                        "Worldline": true,
                        "Legend Stage": true,
                        "BossEvent": true,
                        "Dungeon": true,
                        "Infinite": true,
                        "Rift": true,
                        "Story": true,
                        "Raid": true
                    }
                },
                "Ultimate": {
                    "Enable": false
                }
            },
            "Koguro (Unsealed)": {
                "Elemental Dimensions": {
                    "Enable": true,
                    "Order": {
                        "Fire": 1,
                        "Ice": 2,
                        "Sand": 3
                    }
                }
            },
            "God (Standless)": {
                "Reality Rewrite": {
                    "Enable": true,
                    "Status Effect": "Stun"
                }
            },
            "Skele King (Rock)": {
                "Auto Guitar": {
                    "Enable": true,
                    "Perfect Chance": 96,
                    "Auto King of String": true
                }
            },
            "Song Jinwu and Igros": {
                "Auto Shadow": {
                    "Enable": false,
                    "Order": {
                        "Steel": 2,
                        "Bear": 1,
                        "Healer": 3,
                        "Belu": 4
                    }
                }
            },
            "Hellkiller (Slayer)": {
                "Disable First Person": false,
                "Auto Shoot": false
            },
            "Horsegirls (Racers)": {
                "Enable": false,
                "Horse Type": "Concert",
                "Ignore Chance": 40,
                "Upgrade Prioritize": {
                    "Speed": 4,
                    "Damage": 3,
                    "Crit": 2,
                    "Cost": 1
                }
            },
            "Today's Strongest vs History's Strongest": {
                "Auto Clash": false,
                "Cursed Output": 20,
                "Binding Vows": {
                    "1": false,
                    "2": false,
                    "3": false,
                    "4": true,
                    "5": true,
                    "6": false
                },
                "Clash Winner": "History's Strongest"
            },
            "Elastic Captain (Cog 5th)": {
                "Auto Use Skill": false,
                "Auto Sun God Transformation": false,
                "Use Skill": {
                    "Ultimate2": true,
                    "Skill4": true,
                    "Ultimate1": true,
                    "Skill1": true,
                    "Skill2": true,
                    "Skill5": true,
                    "Skill3": true
                }
            },
            "Raging Oni vs Wrath God": {
                "Auto Clash": false,
                "Clash Winner": "Raging Oni"
            }
        },
        "Auto Skip Wave": {
            "Enable": false,
            "Stop Skip Stage Type": {
                "Odyssey": true,
                "Challenge": true,
                "Portal": true,
                "Worldline": true,
                "Legend Stage": true,
                "BossEvent": true,
                "Dungeon": true,
                "Infinite": true,
                "Rift": true,
                "Story": true,
                "Raid": true
            },
            "Stop at Wave": 0
        },
        "Auto Vote Start": false,
        "Stage Mechanic": {
            "Frozen Volcano": {
                "Upgrade Amount": 0,
                "Auto Friezo": false,
                "Auto Save Brolzi": false,
                "Friezo Unit": {
                    "Bounty Hunter (3 Sword)": false,
                    "Hebano (Clematis)": false,
                    "History's Strongest": false,
                    "Itochi": false,
                    "Boockleo (Evil)": false,
                    "Octopus": false,
                    "Time Goddess (Crazed) Clone": false,
                    "Shinzi": false,
                    "Ali": false,
                    "Sokora": false,
                    "Giant Queen (Founder)": false,
                    "Song Jinwu": false,
                    "Ackers (Ken)": false,
                    "Arc (True Ancestor)": false,
                    "Song Jinwu (Monarch)": false,
                    "Sosuke (Hebi)": false,
                    "Reimu": false,
                    "Agony Shinobi": false,
                    "Tuji (Sorcerer Killer)": false,
                    "Delusional Demon (Blood)": false,
                    "Manipulator (Spider)": false,
                    "Friran": false,
                    "Deruta": false,
                    "Lord (Fairy)": false,
                    "Roku (Super 3)": false,
                    "Haruka Rin": false,
                    "Kazzy": false,
                    "Tuji": false,
                    "Stone Lee": false,
                    "Friran (Teacher)": false,
                    "Diogo": false,
                    "Ackers": false,
                    "Lilia and Berserker": false,
                    "Nobaba": false,
                    "God": false,
                    "Reasonable Person (Calm)": false,
                    "Armored Mage": false,
                    "Cha-In": false,
                    "Reaper": false,
                    "Fastest Shinobi (Flash)": false,
                    "Johnni": false,
                    "Graceful Pilot (Mecha)": false,
                    "Dawntay": false,
                    "Tengon": false,
                    "Saber (Black Tyrant)": false,
                    "Boo": false,
                    "Tengon (Flashiness)": false,
                    "Ishtar (Divinity)": false,
                    "Archer": false,
                    "Monkey King (Awakened)": false,
                    "Time Goddess (Crazed)": false,
                    "Armored Mage (Requip)": false,
                    "Isdead (Romantic)": false,
                    "Savior (Rebirth)": false,
                    "Skele King": false,
                    "Giant Queen": false,
                    "Pickleo": false,
                    "Alocard (Vampire King)": false,
                    "Hebano": false,
                    "Cursed Lawyer": false,
                    "Roku (Dark)": false,
                    "Lizard (Fission)": false,
                    "Arin": false,
                    "Warlord (Of the Sea)": false,
                    "Orehimi (Faith)": false,
                    "Zion (Burdelyon)": false,
                    "Divine General (Adaptation)": false,
                    "Alligator": false,
                    "Lich King (Ruler)": false,
                    "Al": false,
                    "Dodara": false,
                    "Today's Strongest vs History's Strongest": false,
                    "Bootonks (Evil)": false,
                    "God (Standless)": false,
                    "Devoted Demon (Obsessed)": false,
                    "Strongest Shinobi": false,
                    "Emmie": false,
                    "Clatakiri (Mochi)": false,
                    "Emmie (Ice Witch)": false,
                    "Traitless": false,
                    "Slime (King)": false,
                    "Valentine": false,
                    "Sosora": false,
                    "Luce (Hacker)": false,
                    "Song Jinwu and Igros": false,
                    "Thunder (You)": false,
                    "Rabbit Hero (Guts)": false,
                    "Brisket (Yo-Yo)": false,
                    "Monkey King (Clone)": false,
                    "Trash Gamer (Twin Blades)": false,
                    "Delusional Demon": false,
                    "Astolfo": false,
                    "Luce": false,
                    "Demon Hybrid": false,
                    "Astolfo (Rider of Black)": false,
                    "Mechamar": false,
                    "The King": false,
                    "Yehowach (Almighty)": false,
                    "Gujo (Infinity)": false,
                    "Tempest Pirate (Navigator)": false,
                    "Deceiver": false,
                    "Wolf (Resurrection)": false,
                    "Pweeny (Boxer)": false,
                    "Lfelt (Love)": false,
                    "Envoy of Destruction": false,
                    "Inamuki": false,
                    "Hellkiller (Slayer)": false,
                    "Pink Villain (Celestial)": false,
                    "Cursed Shinobi": false,
                    "Kinaru": false,
                    "Savior (Moonless)": false,
                    "Eizan (Aura)": false,
                    "Sosuke (Storm)": false,
                    "Joe": false,
                    "The Falcon (of Darkness)": false,
                    "Ice Manipulator (Admiral)": false,
                    "Grim Wow": false,
                    "Devoted Demon": false,
                    "Ghost Girl": false,
                    "Wrath God": false,
                    "Byeken": false,
                    "Gaari": false,
                    "Kiskae (Scientist)": false,
                    "Vogita Super": false,
                    "Bounty Hunter (King of Hell)": false,
                    "Cat (Stupid)": false,
                    "Super Vogito": false,
                    "Hercool": false,
                    "Boo (Evil)": false,
                    "Totsero (Zombie)": false,
                    "Manipulator": false,
                    "Genitsu": false,
                    "Koguro (Unsealed)": false,
                    "Saber (A.W.E.)": false,
                    "Diogo (Alternate)": false,
                    "Kid Boo (Evil)": false,
                    "Reaper (Scissors)": false,
                    "Rom and Ran (Fanatic)": false,
                    "Goi": false,
                    "Lilia": false,
                    "Giro (Ball Breaker)": false,
                    "Dodara (Explosive)": false,
                    "Vigil (Power)": false,
                    "NotGoodGuy": false,
                    "Obita (Awakened)": false,
                    "Renguko (Purgatory)": false,
                    "Noruto": false,
                    "Rom and Ran": false,
                    "Bomberetta (Zombie)": false,
                    "Akazo": false,
                    "Riner (Reinforced Giant)": false,
                    "Blossom": false,
                    "Jailer": false,
                    "Bounty Hunter": false,
                    "Cat": false,
                    "Zak (Ape Giant)": false,
                    "The Smith": false,
                    "Al (Good)": false,
                    "Dot (Nemesis)": false,
                    "Rummie": false,
                    "Diablo": false,
                    "Jag-o (Volcanic)": false,
                    "World Destroyer (Old)": false,
                    "Gear Boy (Hungry)": false,
                    "Demon Leader (Control)": false,
                    "Elastic Captain": false,
                    "Byeken (Ronin)": false,
                    "Diablo (Renacimiento)": false,
                    "Divalo (Requiem)": false,
                    "The Falcon": false,
                    "Thunder": false,
                    "Kempache": false,
                    "Arbiter": false,
                    "Cursed Doctor": false,
                    "Vigil (Doppelganger)": false,
                    "Zion": false,
                    "LagShooter": false,
                    "Choy Jong En": false,
                    "Saber (Alternate)": false,
                    "Fruit Eater (He Wins)": false,
                    "Black Hole (Ninjutsu)": false,
                    "Ghoul (Winged)": false,
                    "Gujo": false,
                    "Deceiver (Monster)": false,
                    "Yomomata": false,
                    "Club": false,
                    "The Struggler": false,
                    "Saiko": false,
                    "Ackers (Levy)": false,
                    "Elastic Captain (Cog 4th)": false,
                    "Ackers (Makoso)": false,
                    "Roku (Angel)": false,
                    "Explosive Demon (Bomb)": false,
                    "Fallen Angel (Pistols)": false,
                    "The Falcon (Sacrifice)": false,
                    "Pweeny": false,
                    "Lethal Bee": false,
                    "Arin (Rumbling)": false,
                    "Inosake": false,
                    "Elastic Captain (Cog 5th)": false,
                    "Gazelle": false,
                    "Vogita Super (Awakened)": false,
                    "Karem (Chilled)": false,
                    "Priestess": false,
                    "Reimu (Shrine Maid)": false,
                    "Preacher (Hidden Weapon)": false,
                    "Newsman": false,
                    "Cat God (Destruction)": false,
                    "Jon": false,
                    "Shinobi Sage": false,
                    "Lord": false,
                    "Soburo": false,
                    "Company Captain (Hybrid)": false,
                    "Kokashi": false,
                    "Leo (Fangs)": false,
                    "The Struggler (Rampage)": false,
                    "Saber (King of Knights)": false,
                    "Rukio": false,
                    "First Giant": false,
                    "Clatakiri": false,
                    "Mimi": false,
                    "Haruka Rin (Dancer)": false,
                    "Cha-In (Blade Dancer)": false,
                    "Ghost Girl (Umbrella)": false,
                    "Horsegirls (Racers)": false,
                    "Akazo (Destructive)": false,
                    "Vigil": false,
                    "Cat God": false,
                    "Alocard": false,
                    "Shero": false,
                    "Iscanur (Pride)": false,
                    "Dave (Cyber Psycho)": false,
                    "Conqueror vs Invulnerable": false,
                    "Marlin (Gluttony)": false,
                    "Cursed Doctor (Healer)": false,
                    "Regnaw (Rage)": false,
                    "Soburo (Contract)": false,
                    "Archer (Counter Spirit)": false,
                    "Igros (Elite Knight)": false,
                    "Saber": false,
                    "Bean": false,
                    "Ichiga (True Release)": false,
                    "Johnni (Infinite Spin)": false,
                    "Takaroda": false,
                    "Lord Friezo": false,
                    "Club (Pyro)": false,
                    "Nazuka": false,
                    "Oryo": false,
                    "Marlin": false,
                    "Dawntay (Jackpot)": false,
                    "Yuruicha": false,
                    "Zak": false,
                    "Reasonable Person": false,
                    "Demon Hybrid (Chainsaw)": false,
                    "Slime": false,
                    "Igros": false,
                    "Reckless Gambler": false,
                    "Preacher": false,
                    "Kiskae": false,
                    "Obita": false,
                    "Yuruicha (Raijin)": false,
                    "Leo": false,
                    "Gilgamesh": false,
                    "Giyu": false,
                    "Pink Villain": false,
                    "Ice Queen (Release)": false,
                    "Caster": false,
                    "Lord Friezo (Emperor)": false,
                    "Medea": false,
                    "Todu": false,
                    "Riner": false,
                    "Raging Oni vs Wrath God": false,
                    "Foboko": false,
                    "Mohato": false,
                    "Gazelle (Zombie)": false,
                    "Alien Cadet": false,
                    "Smith John": false,
                    "Alien Elite": false,
                    "Kempache (Feral)": false,
                    "Deruta (Hunt)": false,
                    "Trash Gamer": false,
                    "Dot": false,
                    "Renguko": false,
                    "Goblin Killer": false,
                    "Hellkiller": false,
                    "Rudie (Prodigy)": false,
                    "Rule": false,
                    "Dark Mage": false,
                    "Cursed Lawyer (Tired)": false,
                    "Mimi (Psychic)": false,
                    "Shero (Hero of Justice)": false,
                    "Oryo (Antithesis)": false,
                    "Sosora (Puppeteer)": false,
                    "Seban": false,
                    "Karem": false,
                    "Agony Shinobi (Force)": false,
                    "Elastic Captain (Pirate)": false,
                    "Okorun (Turbo)": false,
                    "Vogita": false,
                    "Lord of Shadows": false,
                    "Top Chef": false,
                    "Sprintwagon": false,
                    "Julias": false,
                    "Okorun": false,
                    "Ali (Djinn)": false,
                    "Strongest Shinobi (Martial)": false,
                    "Rogita (Super)": false,
                    "Rodock": false,
                    "Giro": false,
                    "Chaso": false,
                    "Todu (Unleashed)": false,
                    "Jag-o": false,
                    "Agony": false,
                    "Rudie": false,
                    "Rideon vs Samuel (Duel)": false,
                    "Sakuya": false,
                    "Demon Leader": false,
                    "GG": false,
                    "Rogita": false,
                    "Quetzalcoatl": false,
                    "Regnaw": false,
                    "Ichiga": false,
                    "Hollowseph (Pure)": false,
                    "Student (Enraged)": false,
                    "Isdead": false,
                    "NotGoodGuy (Free)": false,
                    "Rogita (Super 4) (Clone)": false,
                    "Saiko (Spirit Medium)": false,
                    "Raging Oni": false,
                    "Priestess (Holy)": false,
                    "Ice Manipulator": false,
                    "Eizan": false,
                    "Fire Foot": false,
                    "Scrap Pirate": false,
                    "Aurin": false,
                    "Quetzalcoatl (Sun God)": false,
                    "Hercool and Mr Boo": false,
                    "Medea (Witch of Betrayal)": false,
                    "Alien Soldier": false,
                    "Choy Jong En (Guild Leader)": false,
                    "Reckless Gambler (Cursed)": false,
                    "Genas": false,
                    "Newsman (Forecast)": false,
                    "Sokora (Angra Mainyu)": false,
                    "Medusa (Gorgon)": false,
                    "The King (Apostle)": false,
                    "Medusa": false,
                    "The Smith (Forged)": false,
                    "Delusional Boy": false,
                    "Fastest Shinobi": false,
                    "Ichiga (Savior)": false,
                    "Fire Foot (Chef)": false,
                    "Skele King (Rock)": false,
                    "Demon Hunter (Contract)": false,
                    "Toad Shinobi (Ribbit)": false,
                    "Unstable (Psychosis)": false,
                    "Scrap Pirate (Metal)": false,
                    "Rule (Surgeon)": false,
                    "Kinnua": false,
                    "Orehimi": false,
                    "Cu Chulainn (Child of Light)": false,
                    "Chaso (Blood Curse)": false,
                    "Hei (Black Dragon)": false,
                    "Lfelt": false,
                    "Black Hole": false,
                    "Goblin Killer (Trapper)": false,
                    "Traitless (Vigilante)": false,
                    "Sakuya (Time Maid)": false,
                    "Rohan (Adult)": false,
                    "Shinobi God (Infinite Dreams)": false,
                    "Teacher (Final Stand)": false,
                    "Senator (Nanomachines)": false,
                    "The Witch": false,
                    "Itaduri": false,
                    "Unstable": false,
                    "Fruit Eater": false,
                    "Valentine (Love Train)": false,
                    "Today's Strongest": false,
                    "Legendary Super Brolzi": false,
                    "Ultimate Rohan": false,
                    "Callasuba": false,
                    "Fallen Angel": false,
                    "Valentine (AU)": false,
                    "Hei": false,
                    "Tempest Pirate": false,
                    "Rogita (Super 4)": false,
                    "Brisket": false,
                    "Noruto (Six Tails)": false,
                    "Shinobi Sage (Friendship)": false,
                    "Beast Pirate (Half-Dragon)": false,
                    "Sukono": false,
                    "Explosive Demon": false,
                    "Demon Hunter": false,
                    "World Destroyer": false,
                    "Boohon (Evil)": false,
                    "Super Boo (Evil)": false,
                    "Vogita (Angel)": false,
                    "Dark Mage (Evil)": false,
                    "Roku": false,
                    "Yomomata (Captain)": false,
                    "Dave": false,
                    "Rabbit Hero": false,
                    "Foboko (Hellish)": false,
                    "Arbiter (Of the Void)": false,
                    "Noruto (Sage)": false,
                    "Lizard": false,
                    "Rummie (Scythe)": false,
                    "Kazzy (Queen)": false,
                    "Toad Shinobi": false,
                    "Gear Boy": false,
                    "Cursed Shinobi (Black Flames)": false,
                    "Callasuba (Squad)": false,
                    "Elastic Pirate": false,
                    "Brolzi Super (Wrathful)": false,
                    "Senator": false,
                    "Arc": false,
                    "Gilgamesh (King of Heroes)": false,
                    "Ishtar": false,
                    "Aurin (Nuclear Giant)": false,
                    "Jailer (Underworld)": false,
                    "GG (Possessed)": false,
                    "Envoy of Destruction (Resistance)": false,
                    "Yehowach": false,
                    "The Falcon (of Light)": false,
                    "Hollowseph": false,
                    "The Witch (Disciple)": false,
                    "Julias (Eisplosion)": false,
                    "Cu Chulainn": false,
                    "Ghoul": false,
                    "God (Above Heaven)": false,
                    "Sosuke": false,
                    "Rideon vs Samuel": false
                },
                "Sell Placed Friezo Unit": false,
                "Leave Extra Money": 5000
            },
            "Double Dungeon": {
                "Auto Statue": true,
                "Statue Unit": {
                    "Bounty Hunter (3 Sword)": false,
                    "Hebano (Clematis)": false,
                    "History's Strongest": false,
                    "Itochi": false,
                    "Boockleo (Evil)": false,
                    "Octopus": false,
                    "Time Goddess (Crazed) Clone": false,
                    "Shinzi": false,
                    "Ali": false,
                    "Sokora": false,
                    "Giant Queen (Founder)": false,
                    "Song Jinwu": false,
                    "Ackers (Ken)": false,
                    "Arc (True Ancestor)": false,
                    "Song Jinwu (Monarch)": false,
                    "Sosuke (Hebi)": false,
      ... (97 KB left)
